#version: "3.8"
services:
  app:
    image: transformers_cuda_12_8_1_g9
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
    #  - /home/avionhp/BOB/ISTAC-CODIGOS-CNO-2025:/app
    #  - d:\BOB\ISTAC-CODIGOS-CNO-2025:/app
    # - c:\BOB\ISTAC-CODIGOS-CNO-2025:/app
    - c:\G9-IA\:/app
    working_dir: /app
    environment:
      - HF_HOME=/app/huggingface # Establece la carpeta de Hugging Face
      - CUDA_VISIBLE_DEVICES=0
    stdin_open: true
    tty: true
    entrypoint: >
      sh -c "/bin/bash"